version: 2
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A fisrt hello"
  # sally:
  #   docker:
  #     - image: circleci/ruby:2.4.1
  #   steps:
  #     - checkout
  #     - run: echo "Double trouble"
